source "https://rubygems.org"

ruby "3.2.2"

gem "sinatra", "~> 3.1"
gem "sinatra-contrib", "~> 3.1"
gem "puma", "~> 6.4"
gem "dotenv", "~> 3.1"

group :development do
  gem "rerun", "~> 0.14"
end

group :test do
  gem "rspec", "~> 3.13"
  gem "rack-test", "~> 2.1"
end

